### ISSUE TITLE
Comparison should happen with the branch point instead of current main branch

### ISSUE THREAD

**Issue by ruudk** [WyriHaximus/github-action-composer.lock-diff#85]
I noticed something weird with this great action (thanks for that 💙):

I merged a PR from Dependabot that upgraded `spaze/phpstan-disallowed-calls` from v2.3.1 to v2.3.2. 

Then a new PR popped up, that upgraded `symfony/dependency-injection` from 6.0.7 to 6.0.8 and this action commented this:
<img width="919" alt="Screenshot 2022-04-28 at 11 19 54@2x" src="https://user-images.githubusercontent.com/104180/165721362-45e11055-ef2c-43a5-bbb6-fac47cd0a257.png">

The top comment is correct, but the bottom comment is not. The PR doesn't downgrade at all! 

The reason for this, is that the action compares against the `composer.json` from `main` at the time of running the action.

Instead, it should not do this at all. It should find the branch point (parent commit) and compare against the `composer.json` from that commit instead.

This is a snippet that I use in another action:
```bash
branchPoint=$(
    git log --no-merges --graph --oneline --decorate origin/main..$(git branch --show-current) | \
    tac | \
    grep -o '[a-f0-9]\{7,11\}' | \
    head -n 1 | \
    xargs -I '{}' git rev-parse "{}^"
)

git show $branchPoint:schema.graphql | cat > schema.old.graphql
```

**Comment by WyriHaximus** [comment]
It's comparing the base ref and head ref: https://github.com/WyriHaximus/github-action-composer.lock-diff/blob/main/entrypoint.sh#L10

**Comment by ruudk** [comment]
I just noticed it happening again, and maybe I know how to reproduce it:

Dependabot opened a PR branched of latest commit in `main`: `63759d`
* Bump phpstan/phpstan-symfony from 1.2.3 to 1.2.4

It displays this:
<img width="788" alt="Screenshot 2022-06-09 at 15 20 50@2x" src="https://user-images.githubusercontent.com/104180/172857052-096d49b9-200d-40d3-ae9c-3ee2a5943c0b.png">
And this is good!

At the same time, there are also 2 other PR's that branched of latest commit in `main`: `63759d`:
* Bump willdurand/geocoder-bundle from 5.17.0 to 5.18.0
* Bump monolog/monolog from 2.6.0 to 2.7.0

These are merged to `main`. 

Now I edit the `phpstan/phpstan-symfony` PR and apply some fixes. I push and now this appears in that PR:
<img width="860" alt="Screenshot 2022-06-09 at 15 22 53@2x" src="https://user-images.githubusercontent.com/104180/172857463-7c926c7f-0199-43ec-852c-86b4148b0fb0.png">

So it does take the changed composer.lock from main and uses that as a compare.

**Comment by WyriHaximus** [comment]
Working on figuring out which SHA to use. But ran into this issue myself as well with a PR that was behind `main` and as such showed a downgraded diff. Exactly the same as your example.

**Comment by WyriHaximus** [comment]
What this action does is compare the `composer.lock` in the `GITHUB_BASE_REF` with the `composer.lock` in the `GITHUB_HEAD_REF`. Now in order to only show changes in the PR is get the parent commit of the first comment in the PR and compare that with the `GITHUB_HEAD_REF`. But that might case the issue the other away around. However the REST API also has the field `merge_commit_sha` which contains the SHA for when the PR would be, or has been merged. (You can see it on this PR (#90) that hasn't merged yet https://api.github.com/repos/WyriHaximus/github-action-composer.lock-diff/pulls/90.)

**Comment by WyriHaximus** [comment]
Opened #91 with the fix for this, still need to test it

**Comment by ruudk** [comment]
Any news on this? Every time I rebase an **older** Dependabot PR (that has this action to post a comment to it) I notice that this problem.

**Comment by WyriHaximus** [comment]
@ruudk Having a look right now after releasing the output updates. Did you by any change tested it using the branch I created for the PR?

**Comment by ruudk** [comment]
No I didn't test it. But I can report back after it's merged+tagged. I should be able to verify within a day if it works as expected.

**Comment by WyriHaximus** [comment]
Cool, will do some verification tonight and tag a release before midnight :+1: .

**Comment by WyriHaximus** [comment]
Bummer, seems they changed some things so I can't get the commit as easy as before. Looking a alternatives in getting the commit from GitHub

**Comment by WyriHaximus** [comment]
@ruudk It took some fiddling but got it working :tada: .

**Comment by WyriHaximus** [comment]
[`v1.3.0`](https://github.com/WyriHaximus/github-action-composer.lock-diff/releases/tag/v1.3.0) is out with the changes for this

**Comment by WyriHaximus** [comment]
That error happens during the REST API calls getting the blob for the merge `composer.lock`, reverting for now while working on a fix with better error handling. The issue with that is if it fails there are two options:
- fail
- gracefully fallback to using `GITHUB_HEAD_REF`

**Comment by ruudk** [comment]
For what it's worth, I use this in my other actions:

```

branchPoint=$(
    git log --no-merges --graph --oneline --decorate origin/main..$(git branch --show-current) | \
    tac | \
    grep -o '[a-f0-9]\{7,11\}' | \
    head -n 1 | \
    xargs -I '{}' git rev-parse "{}^"
)

git show $branchPoint:composer.lock | cat > old-composer.lock
```

No REST API needed. Only a full checkout.

**Comment by WyriHaximus** [comment]
Thanks, will give it a try with that, haven't thought of using rev-parse tbh

**Comment by ruudk** [comment]
@WyriHaximus I know your very busy, but did you have time to try it out? Every now and then I'm reminder that the bug still exists :(

**Comment by WyriHaximus** [comment]
@ruudk I'd sworn I responded with an update :(. IIRC it is possible to use one of the API fields, it however isn't always there. What  I can do is look at waiting a minute or two polling to wait and see if it shows up.

**Comment by ruudk** [comment]
> it is possible to use one of the API fields

Could you tell me which field you are referring to?

Maybe we can ask GitHub via support to answer why.... Then hopefully we can fix it properly (without a timer).

**Comment by WyriHaximus** [comment]
> > it is possible to use one of the API fields
> 
> Could you tell me which field you are referring to?

It is the `merge_commit_sha` property. It's described here (didn't see this last time): https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request 

Reading up on https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-your-git-database?apiVersion=2022-11-28#checking-mergeability-of-pull-requests it seems that this test commit isn't created until someone or something actually checks the PR through the UI or API :facepalm:

**Comment by WyriHaximus** [comment]
> > it is possible to use one of the API fields
> 
> Could you tell me which field you are referring to?

It is the `merge_commit_sha` property. It's described here (didn't see this last time): https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request 

Reading up on https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-your-git-database?apiVersion=2022-11-28#checking-mergeability-of-pull-requests it seems that this test commit isn't created until someone or something actually checks the PR through the UI or API :facepalm:

**Comment by WyriHaximus** [comment]
> > it is possible to use one of the API fields
> 
> Could you tell me which field you are referring to?

It is the `merge_commit_sha` property. It's described here (didn't see this last time): https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request 

Reading up on https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-your-git-database?apiVersion=2022-11-28#checking-mergeability-of-pull-requests it seems that this test commit isn't created until someone or something actually checks the PR through the UI or API :facepalm:

**Comment by ruudk** [comment]
In that case, why not use my branch point snippet?

**Comment by WyriHaximus** [comment]
Tried that, didn't work for some reason. But will try again, might have missed something. IIRC GitHub didn't have that when I tried, but that background job might also be needed for that.

**Comment by WyriHaximus** [comment]
@ruudk With your script, do you also get this warning/error:

```
fatal: ambiguous argument 'origin/main..': unknown revision or path not in the working tree.
```

**Comment by ruudk** [comment]
I think it's because it cannot find the `origin/main` branch, it should work if you checkout with this:
```
-   name: Checkout
    uses: actions/checkout@v3.3.0
    with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
```

**Comment by WyriHaximus** [comment]
@ruudk Thanks! That plus removing `git fetch --depth=1 origin +refs/heads/*:refs/heads/* || true` seems to do the trick for your script. Great! Now I have something confirmed working and understanding why it failed before without having to ping the API :tada: .

**Comment by WyriHaximus** [comment]
Interesting, does this suggest that not presenting a ref it will checkout the merge ref? https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

**Comment by ruudk** [comment]
Why does it has to be composite with multiple checkouts? The readme could instruct the single checkout config needed, right? Keep it simple? 😁

**Comment by WyriHaximus** [comment]
The readme, if I'm correct will just have a single step in the job. Not even the need to check out as I can do that in the composite action. The issue seems that with ```-   name: Checkout
    uses: actions/checkout@v3.3.0
    with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0``` I can't reach the base branch anymore. So if I can get everything inside the action it becomes even simpler 🎉 .

**Comment by WyriHaximus** [comment]
Started giving that idea a go in #114

**Comment by ruudk** [comment]
It seems like #114 is green, did it work?

**Comment by WyriHaximus** [comment]
@ruudk Those were some debugging, I tossed most of the afternoon at it and got to a working proof of concept. That PR's branch is a spicy disaster right now, but it works. So I'll be tidying it up and preparing it for merging and releasing. It will be a new major version because of the switch from docker to composite action.

**Comment by ruudk** [comment]
Before you tag, I can test a commit version if you want? In 2 days I know if it's good or not.

**Comment by WyriHaximus** [comment]
Sure, preparing for exactly that because during testing I notice sometimes wildly differences between the tagged version and #114. Will ping you when it is ready for testing, it might be a bit slower tho as then I don't have to set up Docker image tagging just yet.

**Comment by WyriHaximus** [comment]
@ruudk I'm currently testing out in a project with the following workflow:

```yaml
name: Composer Diff
on:
  ## To make this workflow work in the simplest way possible, without a PAT or juggling information between, we need to
  ## run it with permissions as if it was already merged.
  ## Refs: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  ## Refs: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  ## Refs: https://twitter.com/WyriHaximus/status/1393679576828686340
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
## This workflow needs the `pull-request` permissions to work
## Refs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  pull-requests: write
  contents: read
jobs:
  comment-composer-lock-diff:
    name: Comment composer.lock diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Comment composer.lock diff
        uses: WyriHaximus/github-action-composer.lock-diff@switch-to-composite-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
